name:                99hs
version:             0.1.0.0
github:              "anthony-darienzo/99hs"
license:             BSD3
author:              "Anthony D'Arienzo"
maintainer:          "apd6@illinois.edu"
copyright:           "2021 Anthony D'Arienzo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        See README.md 
dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src

executables:
  99hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 99hs

tests:
  99hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 99hs
